//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentApplicationSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job
    {
        public int jobId { get; set; }
        public string applicantList { get; set; }
        public string jobName { get; set; }
        public Nullable<System.DateTime> applicationStart { get; set; }
        public Nullable<System.DateTime> applicationFinish { get; set; }
    }
}
