//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentApplicationSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class New
    {
        public int newId { get; set; }
        public string header { get; set; }
        public string text { get; set; }
        public byte[] image { get; set; }
        public Nullable<int> featured { get; set; }
        public string featuredList { get; set; }
        public Nullable<System.DateTime> dt_created { get; set; }
        public Nullable<System.DateTime> dt_modified { get; set; }
        public Nullable<int> cd_creater { get; set; }
        public Nullable<int> cd_modifier { get; set; }
        public HttpPostedFileBase imageFile { get; set; }
        public bool BoolValue
        {
            // This function sets the int featured value by using checkbox in forms.
            get { return featured == 1; }
            set { featured = value ? 1 : 0; }
        }
    }
}
