//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentApplicationSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Review
    {
        [Key]
        public int reviewId { get; set; }
        public Nullable<int> userId { get; set; }
        public Nullable<int> paperId { get; set; }
        public Nullable<int> jobId { get; set; }
        public Nullable<int> applicationId { get; set; }
        [DisplayName("Review")]
        public string review1 { get; set; }
        [DisplayName("Status")]
        public string status { get; set; }
        [DisplayName("Interview Date")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy hh:mm tt}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> interviewDate { get; set; }
        [DisplayName("Created")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy hh:mm tt}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> dt_created { get; set; }
        [DisplayName("Modified")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy hh:mm tt}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> dt_modified { get; set; }
        [DisplayName("Created By")]
        public Nullable<int> cd_creater { get; set; }
        [DisplayName("Modified By")]
        public Nullable<int> cd_modifier { get; set; }

        public virtual Application Application { get; set; }
        public virtual InterviewQuestionPaper InterviewQuestionPaper { get; set; }
        public virtual Job Job { get; set; }
        public virtual User User { get; set; }
    }
}